### ISSUE TITLE
Publish dockerhub images as "mozilla/channelserver" rather than "mozilla/pairsona"

### ISSUE THREAD

**Issue by rfk** [mozilla-services/channelserver#26]
We intend for the server component here to be called  "channelserver", but the repo is currently publishing docker images to "mozilla/pairsona" because that's the name of the repo.  Can we please update `$DOCKERHUB_REPO` in circleci config to be "channelserver"?

/cc @jrgm

**Comment by jrconlin** [comment]
Tempted to do the saner thing and just rename this repo. Otherwise folks are going to get lost trying to find "mozilla-services/channelserver"

**Comment by jrconlin** [comment]
Renamed repo as "channelserver".

**Comment by vladikoff** [comment]
@jrconlin could we please trigger a build somehow so that a new `latest` tag gets pushed to https://hub.docker.com/r/mozilla/channelserver/tags/   ?

**Comment by vladikoff** [comment]
Somehow we got a new tag 32 minutes ago but that still uses the old name https://hub.docker.com/r/mozilla/pairsona/tags/

**Comment by rfk** [comment]
May need to update circleci config with the new repo name?

**Comment by jrconlin** [comment]
The problem appears to be that the circleci credentials need to be updated by ops: https://bugzilla.mozilla.org/show_bug.cgi?id=1492646

**Comment by vladikoff** [comment]
this is working!

**Comment by jrconlin** [comment]
thanks @vladikoff
