### ISSUE TITLE
Question: How are we going to deploy updates w/ users already connected?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla-services/channelserver#28]
How are we going to deploy updates when their are users already connected to a channel? Will we deploy a new stack and wait for all users to drain off the old stack before decommissioning it? Will we just break the connection of the existing users and write some reconnect logic that connects to the new stack?

**Comment by rfk** [comment]
At first glance I think the "drain" approach will work better, and should be manageable given that we expect channels to have a short lifetime.

**Comment by jrconlin** [comment]
I suppose it kinda depends on what we consider to be a breaking change. Channel connections will have a maximum lifespan, so once we pull a machine out of active service, the connections will drain "naturally". The channel server also has a URL version component so if there's a significant change we can differentiate for clients, (although I'm not sure if i'd be happy with having "/v102391745/" in the future)

I would also guess that force breaking the connection would be equivalent to a failed connection attempt and that the reconnect dance would have to be re-invoked by the user. Not a super smooth experience, but there can be any number of reasons that the connection fails (network traffic, flaky routers, scanning the wrong code, etc.)

Sorry, a bit rambly answer there, but I'm guessing that the system should be able to handle either case naturally.

**Comment by vladikoff** [comment]
> we expect channels to have a short lifetime.

Pretty much this. 👍
