### ISSUE TITLE
Channels should expire if flow does not complete within a reasonable timeframe

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla-services/channelserver#29]
In the RRA it's noted that we should expect users to take pictures of these QR codes with their cameras. We can expect QR code images to end up in unexpected places, and looked at by unexpected people. One guard we can put in place is to expire a channel if a Supp does not connect or complete the flow within a certain time. Perhaps we say the channel can exist for 15 minutes w/o the Supp connecting, at which point a new channel must be created. Once the Supp connects, give another 15 minutes to complete the flow.

Thoughts?

**Comment by rfk** [comment]
+1; I wonder if it would be more useful to frame it as "channels expire after X minutes of inactivity" rather than have it specifically be about waiting for the second device to connect, as this will help guard against flows that get abandoned part-way through

**Comment by jrconlin** [comment]
I think the server already does this: https://github.com/mozilla-services/channelserver/blob/master/channelserver/src/server.rs#L129

I'd prefer if the timeout was actually a lot less than 15 minutes, to be honest. Heck, might even want to display a countdown timer. 

One thing I'd very much like to avoid is the channelserver retaining knowledge of recently expired channels. Currently, if a channel is connected and there's no counterpart, there's simply no communications performed. For the initiating channel request, that should be preferred, for the connecting request, not getting a response back should fail pretty fast.

**Comment by shane-tomlinson** [comment]
`if party.started.elapsed()` <--- this line is a winner

> "channels expire after X minutes of inactivity

I think it's reasonable to frame this way.

**Comment by rfk** [comment]
@jrconlin the PR wasn't linked here, but I think this was fixed right?

**Comment by jrconlin** [comment]
Yes, it was closed as part of #31. My apologies for missing it in the commit message.
