### ISSUE TITLE
Deploy channel server to dev

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla-services/channelserver#36]

**Comment by jrconlin** [comment]
Filed Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1501853

**Comment by jrconlin** [comment]
May require #43 for QA signoff.

**Comment by rfk** [comment]
from mtg: @jrgm is short on bandwidth, let's check with @jbuck

**Comment by jrconlin** [comment]
Since there's going to be a new version out shortly, going to drop 1501853 in favor of a more generic "Please install latest version to dev".

**Comment by jrconlin** [comment]
Updated https://bugzilla.mozilla.org/show_bug.cgi?id=1501853 to point to release 0.6.0

**Comment by jbuck** [comment]
This is now live at https://dev.channelserver.nonprod.cloudops.mozgcp.net / wss://dev.channelserver.nonprod.cloudops.mozgcp.net/
