### ISSUE TITLE
Improve test_chan integration test suite for QA

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/channelserver#43]
Right now, unit tests for channelserver are a bit limited. `test_chan` opens up a connection to a target server and runs a quick suite of integration tests to proof that things are working correctly.

These need to be expanded and improved.

**Comment by jrconlin** [comment]
Also, consider moving tests to pytest or similar known. (should be reasonably straight forward)

**Comment by jrconlin** [comment]
Tests are added, but not yet confirmed for use by QA.

**Comment by shane-tomlinson** [comment]
@jrconlin - do you think this will be done before Monday? Wondering whether to move it to the "train-126" column in waffle.

**Comment by jrconlin** [comment]
I'm not sure. From what I can tell, running a completely different testing suite from a given application is not really something Travis is set up to deal with well. May want to move to "train-126" for scheduling and I'll see if I can land it early.
