### ISSUE TITLE
Use GCP Geolocation for IP Headers

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/channelserver#44]
See https://cloud.google.com/load-balancing/docs/backend-service#user-defined-request-headers

**Comment by jrconlin** [comment]
Note, should make mmdb an optional data source, and take the header value as preferred.

**Comment by shane-tomlinson** [comment]
> We will need to think about l10n but that should be solvable.

It should be, but we should figure this out sooner rather than later, I wouldn't want to force our l10n team to translate city and town names world-wide, because from the description of `client_city`, this field is in English and there is no "canonical list". Perhaps there's a library that does this already.

> Name of the city from which the request originated, for example, “Mountain View” for Mountain View, California. There is no canonical list of valid values for this variable. The city names may contain US-ASCII letters, numbers, spaces, and the following characters: ``!#$%&'*+-.^_`|~``. 

From the description, the city names will never contain locale specific characters, e.g., an `ñ` in Spanish.

**Comment by jrconlin** [comment]
I suspect that the level of granularity for location is probably the same as the MaxMind DB, so probably draws the line at incorporated cities. I also strongly suspect that the suggested course for getting localization is to use the [Translate service](https://cloud.google.com/translate/pricing), and probably some heavy server side caching. 

I'm guessing that the channel server should probably do the translation based on the UA provided `Accept-Language` header. I'm already doing that for the MaxMind stuff, so not a big deal. I would probably have to add in a DB cache mechanism which might impact initial response time for the first query for an unknown language. I'm also guessing that we'd want to be super careful about checking [some city names](https://en.wikipedia.org/wiki/Wikipedia:Unusual_place_names) like "Intercourse, PA" or "Anus, FR".

**Comment by shane-tomlinson** [comment]
@l-hedgehog raised concerns about using GCP specific headers for this functionality since Moz China's FxA stack will remain in AWS.

**Comment by jrconlin** [comment]
@shane-tomlinson @l-hedgehog, damn good note. To be honest, I don't see these as being replacements, rather, a cascade of "best effort" type attempts. Since the GCP headers will probably be more "up-to-date" than the MaxMind db, I can see using those preferentially, then falling back to doing a MaxMind if GCP comes up empty for whatever reason.

A bit more sensitive question might be determining how we actually localize a locality (e.g. Hong Kong, or disputed areas in the Kashmir). Granted, with some of those spots, not quite sure getting Firefox sync working right is the highest priority item...

**Comment by jrconlin** [comment]
Added w/ #63
