### ISSUE TITLE
Automatically filter private networks from remote IP lookup

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/channelserver#51]
Currently, `get_remote` does not filter private network addresses. These include

10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
127.0.0.1/32

**Comment by rfk** [comment]
Will it work if we just add these explicitly to the list of trusted proxies?

**Comment by jrconlin** [comment]
Yes, in fact, that's the work around that's already in place. That said, we really should filter private network addresses in any case.
