### ISSUE TITLE
chore: Dependency Update for 10/2019

### ISSUE THREAD

**Issue by jrconlin** [mozilla-services/channelserver#77]

**Comment by jrconlin** [comment]
Requires moving to actix 1.0. 
Going to pair with @fzzzy to do an estimate on work for this.

**Comment by fzzzy** [comment]
Let's shelve this for now until sync is out the door.

**Comment by jrconlin** [comment]
Make that Actix 2.0

**Comment by jrconlin** [comment]
TODO:

- [ ] restore functions in main & server
- [ ] original unit tests pass
- [ ] fix logging calls
- [ ] fix metric calls
- [ ] remove detrius code and elements
- [ ] opt: restore session.rs?
- [ ] fmt code
- [ ] fix docs

**Comment by pjenvey** [comment]
closed in #78
